apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  postgresql.conf: |-
{{- nindent 4 .Values.config.postgresqlConf }}
  pg_hba.conf: |-
{{- nindent 4 .Values.config.pgHbaConf }}
