{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql-cdc.fullname" . }}
  labels:
    {{- include "mysql-cdc.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ required "auth.rootPassword is required when auth.existingSecret is not set" .Values.auth.rootPassword | b64enc | quote }}
  {{- if .Values.auth.password }}
  mysql-password: {{ .Values.auth.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.username }}
  mysql-username: {{ .Values.auth.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.database }}
  mysql-database: {{ .Values.auth.database | b64enc | quote }}
  {{- end }}
{{- end }}
