{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mysql-cdc.serviceAccountName" . }}
  labels:
    {{- include "mysql-cdc.labels" . | nindent 4 }}
{{- end }}
