apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql-cdc.fullname" . }}
  labels:
    {{- include "mysql-cdc.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: mysql
      protocol: TCP
  selector:
    {{- include "mysql-cdc.selectorLabels" . | nindent 4 }}
{{- if .Values.service.headless.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql-cdc.headlessServiceName" . }}
  labels:
    {{- include "mysql-cdc.labels" . | nindent 4 }}
  {{- with .Values.service.headless.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: mysql
      protocol: TCP
  selector:
    {{- include "mysql-cdc.selectorLabels" . | nindent 4 }}
{{- end }}
