apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  {{- $anno := dict -}}
  {{- with .Values.service.annotations }}
    {{- range $k, $v := . }}
      {{- $_ := set $anno $k $v -}}
    {{- end }}
  {{- end }}
  {{- $issuerName := default "" .Values.tls.certManager.issuerRef.name -}}
  {{- if $issuerName }}
    {{- $_ := set $anno "cert-manager.io/cluster-issuer" $issuerName -}}
  {{- end }}
  {{- if gt (len $anno) 0 }}
  annotations:
    {{- toYaml $anno | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with .Values.service.clusterIPs }}
  clusterIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: mongodb
      port: {{ .Values.service.port }}
      targetPort: mongodb
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    {{- include "mongodb.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}-headless
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  {{- $headlessAnno := dict -}}
  {{- $issuerName := default "" .Values.tls.certManager.issuerRef.name -}}
  {{- if $issuerName }}
    {{- $_ := set $headlessAnno "cert-manager.io/cluster-issuer" $issuerName -}}
  {{- end }}
  {{- if gt (len $headlessAnno) 0 }}
  annotations:
    {{- toYaml $headlessAnno | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: mongodb
      port: {{ .Values.service.port }}
      targetPort: mongodb
  selector:
    {{- include "mongodb.selectorLabels" . | nindent 4 }}
